/* 执行归档独立于 review-snapshot1；原始字节保留，恢复副本明确要求重新核实。 */
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),C=require('./report_contract.cjs'),E=require('./execution_plan.cjs'),store=require('./task_store.cjs');
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),write=(f,v)=>fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
function archive(taskFile,destination,{complete=false,context}={}){const initial=E.load(taskFile);return store.locked(initial.root,'execution-archive',()=>{
 const ctx=E.load(taskFile);destination=path.resolve(destination);if(fs.existsSync(destination))throw Error('归档目录已存在');if(complete)E.production(ctx,'package');
 const sources=new Map(),queue=[];function add(file){file=fs.realpathSync(file);if(!fs.statSync(file).isFile())throw Error('归档引用不是文件：'+file);if(!sources.has(file)){const entry={source:file,record:'files/'+crypto.randomUUID()+path.extname(file),sha256:C.fileHash(file)};sources.set(file,entry);queue.push(file);}}
 add(ctx.taskFile);add(ctx.file);
 function walk(value,base,key){if(Array.isArray(value)){for(const x of value)walk(x,base,key);return;}if(value&&typeof value==='object'){for(const [k,v]of Object.entries(value))walk(v,base,k);return;}if(typeof value!=='string'||!['record','path','rootTask','taskFile','output','html','pdf','auditFile','reviewFile','receipt','inputRefs'].includes(key))return;const file=path.resolve(base,value);if(fs.existsSync(file)&&fs.statSync(file).isFile())add(file);}
 for(let n=0;n<queue.length;n++){const file=queue[n];if(path.extname(file)==='.json'){const value=read(file),base=value.id===ctx.plan.id&&value.items?ctx.dir:path.dirname(file);walk(value,base);}else if(/\.html?$/.test(file)){const task=C.read(fs.readFileSync(file,'utf8'));if(task)walk(task,path.dirname(file));}}
 /* 历史与失败操作同样是恢复线索，但绝不作为有效产物索引。 */
 const history=path.join(ctx.root,'execution-history');if(fs.existsSync(history))for(const n of fs.readdirSync(history))add(path.join(history,n));
 fs.mkdirSync(destination,{recursive:true});try{
  for(const e of sources.values()){const to=path.join(destination,e.record);fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(e.source,to,fs.constants.COPYFILE_EXCL);if(C.fileHash(to)!==e.sha256||C.fileHash(e.source)!==e.sha256)throw Error('归档期间源文件变化');}
  let reviewed=null;try{const r=E.currentReview(ctx);reviewed=require('./snapshot_review.cjs').snapshotReview({auditFile:r.auditFile,reviewFile:r.reviewFile,outputDir:path.join(destination,'reviewed')});}catch(e){if(complete)throw e;}
  const manifest={schemaVersion:1,kind:'execution-bundle',status:complete?'complete':'checkpoint',planId:ctx.plan.id,revision:ctx.plan.revision,rootTask:ctx.taskFile,planFile:ctx.file,files:[...sources.values()],reviewed:reviewed?'reviewed':null,createdAt:new Date().toISOString(),recovery:'原始字节只读；移动恢复生成待复核工作副本，不继承未核实的生产状态'};
  write(path.join(destination,'execution-bundle.json'),manifest);verify(destination);return {status:manifest.status,directory:destination,manifest:path.join(destination,'execution-bundle.json')};
 }catch(e){fs.rmSync(destination,{recursive:true,force:true});throw e;}
 },context);}
function verify(directory){directory=fs.realpathSync(directory);const m=read(path.join(directory,'execution-bundle.json'));if(m.schemaVersion!==1||m.kind!=='execution-bundle'||!['checkpoint','complete'].includes(m.status)||!Array.isArray(m.files))throw Error('执行归档合同无效');const seen=new Set();for(const e of m.files){const file=path.resolve(directory,e.record);if(!file.startsWith(directory+path.sep)||seen.has(e.source)||C.fileHash(file)!==e.sha256)throw Error('执行归档缺失/变化/重复引用');seen.add(e.source);}if(!seen.has(m.rootTask)||!seen.has(m.planFile))throw Error('归档缺少根任务或计划');if(m.reviewed)require('./snapshot_review.cjs').loadSnapshot(path.resolve(directory,m.reviewed));if(m.status==='complete'&&!m.reviewed)throw Error('完整执行归档缺少审查快照');return m;}
function restore(directory,destination){const m=verify(directory);destination=path.resolve(destination);if(fs.existsSync(destination))throw Error('恢复目标必须为新目录');fs.mkdirSync(destination,{recursive:true});
 try{const mapping=new Map(m.files.map(e=>[e.source,path.join(destination,e.record)]));for(const e of m.files){const to=mapping.get(e.source);fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(path.resolve(directory,e.record),to,fs.constants.COPYFILE_EXCL);}
 const oldTask=read(mapping.get(m.rootTask)),oldPlan=read(mapping.get(m.planFile)),task=structuredClone(oldTask),plan=structuredClone(oldPlan),rootFile=path.join(destination,'task.json'),planFile=path.join(destination,'execution-plan.json');
 const sourceBase=path.dirname(m.rootTask),oldPlanBase=path.dirname(m.planFile);
 for(const key of ['blueprint','analysisReview'])if(task[key]?.record){const original=path.resolve(sourceBase,task[key].record),copied=mapping.get(original);if(!copied)throw Error('恢复缺少 '+key);task[key]={record:path.relative(destination,copied),sha256:C.fileHash(copied)};}
 if(task.blueprint){const bp=path.resolve(destination,task.blueprint.record),doc=read(bp),original=path.resolve(sourceBase,oldTask.blueprint.record);for(const a of doc.artifacts||[]){const copy=mapping.get(path.resolve(path.dirname(original),a.path));if(!copy)throw Error('恢复缺少分析附件：'+a.path);a.path=path.relative(path.dirname(bp),copy);}store.atomic(bp,JSON.stringify(doc,null,2)+'\n');task.blueprint.sha256=C.fileHash(bp);}
 task.pages={record:'pages.json'};task.executionPlan={id:m.planId,record:'execution-plan.json'};delete task.analysisPreview;
 plan.rootTask='task.json';plan.revision++;plan.scopeRevision++;plan.productionRefs={};plan.decisions.push({kind:'restore',sourceBundle:C.fileHash(path.join(directory,'execution-bundle.json')),reason:'文件位置改变；保留历史声明，重建制作与当前证据。已审版本保存在 reviewed 快照。'});
 for(const item of plan.items){if(item.inputRefs)item.inputRefs=item.inputRefs.map(r=>{const f=mapping.get(path.resolve(oldPlanBase,r));if(!f)throw Error('恢复缺少工作输入：'+r);return path.relative(destination,f);});if(item.evidenceRefs)item.evidenceRefs=item.evidenceRefs.map(r=>({...r,record:path.relative(destination,mapping.get(path.resolve(oldPlanBase,r.record))||path.join(destination,'missing-evidence'))}));if(item.attempt){(item.attemptHistory??=[]).push({...item.attempt,state:'status_unknown'});delete item.attempt;if(item.state==='in_progress')item.state='pending';}}
 write(rootFile,C.normalize(task));write(planFile,plan);write(path.join(destination,'restore-provenance.json'),m);if(m.reviewed)fs.cpSync(path.join(directory,m.reviewed),path.join(destination,'reviewed'),{recursive:true,errorOnExist:true});return {status:'needs_revalidation',taskFile:rootFile,planId:m.planId,revision:plan.revision,reviewed:m.reviewed?path.join(destination,'reviewed'):null};
 }catch(e){fs.rmSync(destination,{recursive:true,force:true});throw e;}}
function adopt(taskFile,destination){taskFile=fs.realpathSync(taskFile);const source=C.normalize(read(taskFile));if(source.version!==3)throw Error('旧 task1/2 请先使用 migrate_strict_analysis.cjs 迁至 task3，再显式接入执行计划');if(source.executionPlan)throw Error('已有执行计划，请使用 checkpoint/恢复');destination=path.resolve(destination);if(fs.existsSync(destination))throw Error('接入目标必须为新目录');fs.mkdirSync(destination,{recursive:true});try{const task=structuredClone(source),sourceBase=path.dirname(taskFile);fs.copyFileSync(taskFile,path.join(destination,'original-task.json'));const original=path.resolve(sourceBase,task.blueprint.record),doc=read(original);for(const [index,a]of (doc.artifacts||[]).entries()){const from=path.resolve(path.dirname(original),a.path),to='artifact-'+index+path.extname(from);fs.copyFileSync(from,path.join(destination,to));a.path=to;}write(path.join(destination,'blueprint.json'),doc);task.blueprint={record:'blueprint.json'};if(task.analysisReview){fs.copyFileSync(path.resolve(sourceBase,task.analysisReview.record),path.join(destination,'analysis-review.json'));task.analysisReview={record:'analysis-review.json',sha256:C.fileHash(path.join(destination,'analysis-review.json'))};}task.pages={record:'pages.json'};task.policyVersions.workflow='execution-plan-1';task.executionPlan={id:crypto.randomUUID(),record:'execution-plan.json'};delete task.analysisPreview;write(path.join(destination,'task.json'),C.normalize(task));write(path.join(destination,'execution-plan.json'),E.create(task));return {status:'draft',taskFile:path.join(destination,'task.json'),note:'原任务未修改；新增 workflow 后须重新制作与审查，不补签历史进度'};}catch(e){fs.rmSync(destination,{recursive:true,force:true});throw e;}}
module.exports={archive,verify,restore,adopt};
