'use strict';
const assert=require('node:assert/strict');
const blueprint=require('./deck_blueprint.cjs'), content=require('./content_contract.cjs');
const {fixture,task}=require('../tests/fixtures/analysis_fixture.cjs');
const copy=v=>JSON.parse(JSON.stringify(v));
function check(d,stage='research'){return blueprint.validate(d,{task,stage,preview:true});}
const draft=fixture();draft.slides=[];draft.claims=[];draft.analysis.workItems[0].status='planned';draft.analysis.workItems[0].outputClaimRefs=[];draft.analysis.issues[0].disposition='open';draft.analysis.synthesis={answerClaimRefs:[],openIssueRefs:[],basis:''};
assert.equal(check(draft).status,'PASS','研究草稿不应先要求页面和结论');
assert.equal(blueprint.validate(fixture(),{task:{...task,version:1},stage:'research'}).status,'FAIL');
const d=fixture();assert.equal(check(d,'ready').status,'PASS',JSON.stringify(check(d,'ready')));
const pages=content.compile(d,{task,preview:true});
assert.ok(Math.abs(pages.pages[0].content.metrics.find(m=>m.id==='growth-rate').value-20)<1e-10);
const pending=copy(d.claims[0]);pending.id='unused';pending.metrics=[];pending.statement='未采纳研究';pending.verification='pending';d.claims.push(pending);
assert.equal(check(d,'ready').status,'PASS','未选用研究可以保持 pending');
d.claims[0].verification='pending';assert.equal(check(d,'ready').status,'FAIL','采纳的主张不能 pending');
const workOutput=fixture();workOutput.claims.push(copy(pending));workOutput.analysis.workItems[0].outputClaimRefs.push('unused');
assert.ok(check(workOutput,'synthesis').errors.some(e=>e.includes('采纳依赖仍 pending：unused')),'已采纳工作的所有登记产出均须核实');
const dep=fixture();dep.claims[0].metrics.push({id:'hidden-input',unit:'倍',decimals:0,value:1});dep.claims.push({...copy(pending),id:'indirect',metrics:[{id:'pending-input',unit:'倍',decimals:0,value:2}]});dep.claims[0].metrics[2].formula={op:'multiply',args:['base','pending-input']};assert.equal(check(dep,'ready').status,'FAIL','公式间接输入不能绕过核实');
const gap=fixture();gap.analysis.gaps.push({id:'cost-gap',description:'内部成本',route:'user',affectedRefs:['revenue-change'],blockingScope:'branch',status:'waiting_user',request:{channel:'request_user_input_async',locator:'turn-1'}});assert.equal(check(gap,'synthesis').status,'FAIL');
gap.analysis.gaps[0].affectedRefs=['unused'];gap.claims.push(copy(pending));assert.equal(check(gap,'synthesis').status,'PASS','无关分支可继续');
gap.analysis.gaps[0].status='resolved';assert.equal(check(gap,'research').status,'FAIL','空回复不能解决缺口');
const bad=fixture();bad.claims[1].metrics[0].id='base';assert.equal(check(bad).status,'FAIL','全局指标 ID 唯一');
const collidingMetric=fixture();collidingMetric.claims[0].metrics[0].id='revenue-issue';
assert.ok(check(collidingMetric).errors.some(e=>e.includes('metric id 须全局唯一')),'指标与问题等其他实体不能共用 ID，避免缺口归属混淆');
const gapToGap=fixture();gapToGap.analysis.gaps.push({id:'pending-gap',description:'另一缺口',route:'bounded',affectedRefs:[],blockingScope:'none',status:'unavailable',resolution:{basis:'尚无数据'}});
gapToGap.analysis.gaps.push({id:'missing-input',description:'待用户输入',route:'user',affectedRefs:['pending-gap'],blockingScope:'branch',status:'waiting_user',request:{channel:'request_user_input_async',locator:'turn-gap'}});
assert.ok(check(gapToGap,'synthesis').errors.some(e=>e.includes('gap.affectedRefs 未登记：missing-input')),'缺口不能把另一缺口当受影响依赖');
const noLeak=fixture();noLeak.slides[1].claimRefs=['revenue-change'];noLeak.slides[1].metricRefs=['growth-rate'];const p=content.compile(noLeak,{task,preview:true});assert.ok(!p.pages[0].content.metrics.some(m=>m.id==='forecast-revenue'));
const analysis=require('./analysis_contract.cjs');const layout=fixture();layout.slides[1].visual.primary='新展示说明';assert.equal(analysis.digest(layout),analysis.digest(fixture()));
const unfinished=fixture();unfinished.analysis.workItems[0].status='planned';unfinished.analysis.workItems[0].outputClaimRefs=[];unfinished.analysis.workItems[0].counterEvidence='';
assert.deepEqual(analysis.adopted(unfinished).workItemRefs,['revenue-work'],'已回答的重要问题须采纳其登记工作');
assert.equal(check(unfinished,'synthesis').status,'FAIL','重要问题关联的工作未完成不得综合');
unfinished.analysis.gaps.push({id:'work-gap',description:'缺少工作输入',route:'user',affectedRefs:['revenue-work'],blockingScope:'branch',status:'waiting_user',request:{channel:'request_user_input_async',locator:'turn-work'}});
assert.equal(check(unfinished,'ready').status,'FAIL','等待用户的已采纳工作缺口不得进入生产');
const oneSided=copy(unfinished);oneSided.analysis.issues[0].workItemRefs=[];
assert.ok(check(oneSided,'synthesis').errors.some(e=>e.includes('issue/workItem 关联须双向一致')),'只在 workItem 一侧登记问题不得绕过工作门禁');
const otherSide=copy(unfinished);otherSide.analysis.workItems[0].issueRefs=[];
assert.ok(check(otherSide,'research').errors.some(e=>e.includes('issue/workItem 关联须双向一致')),'只在 issue 一侧登记工作也须报关联不一致');
const child=copy(unfinished);child.analysis.issues[0].workItemRefs=[];child.analysis.workItems[0].issueRefs=['cost-child'];
child.analysis.issues.push({id:'cost-child',parentRef:'revenue-issue',question:'子问题的未完成工作',priority:'medium',disposition:'answered',workItemRefs:['revenue-work']});
assert.deepEqual(analysis.adopted(child).workItemRefs,['revenue-work'],'已回答父问题须沿子问题采纳工作');
assert.ok(check(child,'synthesis').errors.some(e=>e.includes('采纳工作未完成：revenue-work')),'子问题未完成工作不得绕过综合门禁');
const openChild=copy(child);openChild.analysis.issues[1].disposition='open';openChild.analysis.issues[1].workItemRefs=[];openChild.analysis.workItems[0].issueRefs=[];
assert.ok(check(openChild,'synthesis').errors.some(e=>e.includes('已采纳问题未裁决：cost-child')),'已采纳的开放子问题须明确列为未决');
const bounded=copy(unfinished);bounded.analysis.issues[0].disposition='bounded';bounded.analysis.issues[0].basis='当前证据只能支持有限结论';bounded.analysis.gaps=[];
assert.equal(check(bounded,'synthesis').status,'PASS','已明确收窄的问题可保留未完成工作');
console.log('PASS analysis: stages, global metrics, pending closure, gap waits, visible projection, analysis digest');
module.exports={fixture,task};
