/* 行为/状态合同回归。人工验收内容均为合成夹具，不是实际报告审查。 */
'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const api=require('./report.cjs'),E=require('./execution_plan.cjs'),C=require('./report_contract.cjs'),R=require('./execution_requirements.cjs');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'forge-execution-')),dir=path.join(root,'task'),read=f=>JSON.parse(fs.readFileSync(f,'utf8')),write=(f,v)=>fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n');
async function main(){try{
 for(const mode of ['editorial','analytical','exploratory']){const d=path.join(root,mode);api.initialize(d,{workMode:mode});const p=read(path.join(d,'execution-plan.json'));assert.ok(p.items.some(i=>i.id==='chart-diversity'));assert.ok(p.items.some(i=>i.id==='layout-diversity'));assert.ok(p.items.some(i=>i.id==='module-fill'));assert.ok(p.items.some(i=>i.id==='module-fill-plan'));assert.equal(p.items.some(i=>i.id==='analysis-review'),mode!=='editorial');}
 api.initialize(dir);const taskFile=path.join(dir,'task.json'),planFile=path.join(dir,'execution-plan.json'),task=read(taskFile);let n=0;
 const update=ops=>E.update(taskFile,{operationId:'test-'+(++n),expectedRevision:read(planFile).revision,ops});
 assert.equal(task.policyVersions.workflow,'execution-plan-2');assert.equal(E.status(taskFile).state,'draft');assert.throws(()=>E.assertGate(task,dir,'ready'),/未激活/);
 const badRecord=path.join(dir,'bad-production.json');write(badRecord,{operation:'compile',status:'failed',taskFile,inputDigest:E.inputs(E.load(taskFile)),result:{}});assert.throws(()=>E.recordProduction(taskFile,badRecord),/未成功发布/);const foreign=path.join(root,'foreign');api.initialize(foreign);write(badRecord,{operation:'compile',status:'published',taskFile:path.join(foreign,'task.json'),inputDigest:E.inputs(E.load(taskFile)),result:{}});assert.throws(()=>E.recordProduction(taskFile,badRecord),/其他计划/);assert.deepEqual(read(planFile).productionRefs,{});
 const original=fs.readFileSync(planFile);E.status(taskFile);E.status(taskFile,{resume:true});assert.deepEqual(fs.readFileSync(planFile),original);
 for(const edit of [p=>p.requirements.pop(),p=>p.requirements[0].mandatory=false,p=>p.items=p.items.filter(i=>i.id!=='chart-diversity'),p=>p.items.find(i=>i.id==='layout-plan').state='cancelled',p=>p.items.find(i=>i.id==='analysis').state='done']){const p=read(planFile);edit(p);assert.throws(()=>E.validate(p,task));}
 const legacyTask={...task,policyVersions:{...task.policyVersions,workflow:'execution-plan-1'}},legacyPlan=E.create(legacyTask);assert.equal(legacyPlan.requirements.length,2);assert.ok(!legacyPlan.items.some(i=>i.id==='module-fill'));assert.deepEqual(E.validate(legacyPlan,legacyTask),legacyPlan);assert.throws(()=>E.validate(legacyPlan,task),/固定要求/);assert.ok(R.items(task).find(i=>i.id==='representatives').dependsOn.includes('module-fill-plan'));assert.ok(R.items(task).find(i=>i.id==='package').dependsOn.includes('module-fill'));
 const strict=C.normalize({...task,executionPlan:undefined,policyVersions:{...require('./contract_capabilities.cjs').DEFAULT_POLICIES}});assert.equal(strict.policyVersions.workflow,undefined);
 // 制作观察必须绑定当前装配字节；旧 HTML 不能借“文件仍存在”继续保持完成。
 const inspectProduction=E.load(taskFile),currentHtml=path.join(dir,'current.html'),staleHtml=path.join(dir,'stale.html'),productionEvidence=path.join(dir,'production-observation.json');
 fs.writeFileSync(currentHtml,'<html>current</html>');fs.writeFileSync(staleHtml,'<html>stale</html>');
 const productionItem={id:'production-binding-test',title:'合成制作观察',phase:'production',criterion:'production',state:'done',requirementRefs:[],dependsOn:[],evidenceRefs:[]};
 inspectProduction.plan.items.push(productionItem);inspectProduction.plan.productionRefs.assemble={files:{html:E.ref(inspectProduction,currentHtml)},inputDigest:E.inputs(inspectProduction)};
 const observed=file=>{write(productionEvidence,{kind:'production',reviewer:'synthetic',basis:'合成当前装配校验',files:[E.ref(inspectProduction,file)]});productionItem.evidenceRefs=[{...E.ref(inspectProduction,productionEvidence),inputDigest:E.inputs(inspectProduction,productionItem)}];return E.effective(inspectProduction).find(i=>i.id===productionItem.id);};
 assert.equal(observed(staleHtml).status,'needs_revalidation');assert.equal(observed(currentHtml).status,'done');
 assert.throws(()=>C.normalize({...task,executionPlan:{...task.executionPlan,revision:1}}),/id\/record/);assert.throws(()=>C.normalize({...task,policyVersions:{...task.policyVersions,workflow:'future'}}));for(const workflow of [['execution-plan-1'],{},null,1])assert.throws(()=>C.normalize({...task,policyVersions:{...task.policyVersions,workflow}}));
 update([{action:'activate',intake:{goal:'测试完整恢复',scope:'合成任务',deliverables:'HTML/PDF',constraints:'固定多样性',approach:'先分析再制作',nextStep:'整理输入',openQuestions:[]}}]);
 const request={operationId:'idempotent',expectedRevision:read(planFile).revision,ops:[{action:'decision',text:'合成幂等操作'}]};const result=E.update(taskFile,request);assert.equal(E.update(taskFile,request).status,'already-applied');assert.equal(read(planFile).revision,result.revision);assert.throws(()=>E.update(taskFile,{...request,ops:[{action:'decision',text:'不同内容'}]}),/不同请求/);assert.throws(()=>E.update(taskFile,{...request,operationId:'stale'}),/expectedRevision/);
 update([{action:'add',id:'research-a',item:{title:'研究 A',phase:'analysis',criterion:'files',completionCriteria:'确认文件字节',inputRefs:[],requirementRefs:[]}}]);update([{action:'delegate',id:'research-a',owner:'synthetic-worker'}]);let attempt=read(planFile).items.find(i=>i.id==='research-a').attempt;
 assert.equal(E.status(taskFile,{resume:true}).items.find(i=>i.id==='research-a').status,'status_unknown');
 const artifact=path.join(dir,'result.txt');fs.writeFileSync(artifact,'synthetic evidence');const evidence=path.join(dir,'observation.json');write(evidence,{kind:'files',reviewer:'synthetic-worker',basis:'合成文件校验',files:[{record:'result.txt',sha256:C.fileHash(artifact)}]});
 assert.throws(()=>update([{action:'submit',id:'research-a',attemptId:'late-attempt',evidence:'observation.json'}]),/attempt/);
 update([{action:'submit',id:'research-a',attemptId:attempt.id,evidence:'observation.json'}]);assert.equal(E.status(taskFile).items.find(i=>i.id==='research-a').status,'submitted');assert.throws(()=>update([{action:'accept',id:'research-a'}]),/接收/);
 update([{action:'accept',id:'research-a',reviewer:'synthetic-main',basis:'核对合成文件'}]);assert.equal(E.status(taskFile).items.find(i=>i.id==='research-a').status,'done');
 fs.writeFileSync(artifact,'changed');assert.equal(E.status(taskFile).items.find(i=>i.id==='research-a').status,'needs_revalidation');
 update([{action:'reopen',id:'research-a',reason:'输入变化'},{action:'delegate',id:'research-a',owner:'worker-2'}]);const second=read(planFile).items.find(i=>i.id==='research-a').attempt;assert.notEqual(attempt.id,second.id);assert.throws(()=>update([{action:'submit',id:'research-a',attemptId:attempt.id,evidence:'observation.json'}]),/attempt/);
 update([{action:'scope',reason:'用户修改范围'}]);assert.throws(()=>update([{action:'submit',id:'research-a',attemptId:second.id,evidence:'observation.json'}]),/过期/);
 assert.throws(()=>update([{action:'cancel',id:'chart-plan',reason:'简单报告'}]),/不能取消/);
 assert.throws(()=>update([{action:'add',id:'cycle',item:{title:'循环',phase:'analysis',criterion:'files',completionCriteria:'测试',dependsOn:['cycle']}}]),/循环/);
 assert.ok(fs.readdirSync(path.join(dir,'.forge/execution-history')).length>5);
 update([{action:'add',id:'cancelled-task',item:{title:'已取消工作',phase:'analysis',criterion:'files',completionCriteria:'合成取消测试'}}]);update([{action:'cancel',id:'cancelled-task',reason:'用户取消此范围'}]);assert.throws(()=>update([{action:'start',id:'cancelled-task'}]),/reopen/);assert.equal(E.status(taskFile,{resume:true}).items.find(i=>i.id==='cancelled-task').reason,'用户取消此范围');assert.equal(E.status(taskFile,{resume:true}).intake.goal,'测试完整恢复');
 const savedHistory=path.join(root,'saved-plan.json');write(savedHistory,read(planFile));const damaged=read(planFile);damaged.items=damaged.items.filter(i=>i.id!=='chart-plan');write(planFile,damaged);assert.throws(()=>E.load(taskFile),/缺少固定/);assert.equal(E.restore(taskFile,savedHistory).status,'restored');assert.ok(fs.readdirSync(dir).some(n=>n.startsWith('execution-plan.json.corrupt-')));
 const linkedInput=path.join(fs.realpathSync(dir),'linked-result.txt');fs.symlinkSync('result.txt',linkedInput);
 update([{action:'add',id:'linked-input',item:{title:'符号链接输入',phase:'analysis',criterion:'files',completionCriteria:'移动后仍可读取输入',inputRefs:['result.txt','linked-result.txt']}}]);
 const checkpoint=path.join(root,'bundle');require('./execution_archive.cjs').archive(taskFile,checkpoint);const bundle=require('./execution_archive.cjs').verify(checkpoint);assert.equal(bundle.status,'checkpoint');assert.equal(bundle.files.filter(e=>e.source===fs.realpathSync(artifact)).length,1);assert.ok(bundle.files.find(e=>e.source===fs.realpathSync(artifact)).aliases.includes(linkedInput));
 fs.renameSync(dir,dir+'-unavailable');const restored=require('./execution_archive.cjs').restore(checkpoint,path.join(root,'restored'));assert.equal(restored.planId,task.executionPlan.id);const state=E.status(restored.taskFile,{resume:true});assert.equal(state.requirements.length,3);assert.equal(state.status,'ACTION_REQUIRED');assert.equal(state.items.find(i=>i.id==='research-a').status,'pending');
 const raw=read(path.join(root,'restored/execution-plan.json'));assert.ok(raw.decisions.some(d=>d.kind==='restore'));const linked=raw.items.find(i=>i.id==='linked-input');assert.equal(linked.inputRefs[0],linked.inputRefs[1]);assert.equal(fs.readFileSync(path.resolve(path.dirname(restored.taskFile),linked.inputRefs[1]),'utf8'),'changed');
 // 归档校验须拒绝逃出目录的符号链接，即使目标字节仍与清单一致。
 const archivedInput=bundle.files.find(e=>e.aliases?.includes(linkedInput)),archivedPath=path.join(checkpoint,archivedInput.record),outside=path.join(root,'outside-input.txt');fs.copyFileSync(archivedPath,outside);fs.unlinkSync(archivedPath);fs.symlinkSync(outside,archivedPath);assert.throws(()=>require('./execution_archive.cjs').verify(checkpoint),/执行归档/);
 // 同一 plan id 在各基准目录往返改写，摘要不绑定 locator。
 const from=path.join(root,'one'),to=path.join(root,'two'),rebased=C.rebaseAnalysisTask(task,from,to);assert.equal(path.resolve(to,rebased.executionPlan.record),path.resolve(from,task.executionPlan.record));
 const snap={pages:[{page:1,pageId:'p',content:'hello',styles:[]}],dependencies:{}};const img=path.join(root,'image.png');fs.writeFileSync(img,'fixture');const man=t=>require('./audit_evidence.cjs').manifest(snap,[{screenshot:img}],[{page:1,path:img}],{html:{sha256:'a'},pdf:{sha256:'b'}},t,root,{});assert.equal(man(task).dependenciesSha256,man({...task,executionPlan:{...task.executionPlan,record:'other/place.json'}}).dependenciesSha256);
 const q=require('./execution_quality.cjs'),audit={taskContract:{...task,policyVersions:{...task.policyVersions,workflow:'execution-plan-1'},complexity:'simple',majorConclusion:true,reviewPolicy:undefined},evidenceManifest:{entries:[{id:'html:p',pageId:'p'},{id:'pdf:p',pageId:'p'}]}};
 const quality=role=>R.FIXED.map(r=>({id:r.id,independence:role,reviewer:role,status:'pass',basis:'合成检查',evidenceIds:['html:p','pdf:p'],observations:[{pageId:'p',observed:'合成所见',considered:'其他合适形式',decision:'保留依据'}],repetitions:[]}));let review={qualityChecks:quality('author'),coverage:[{independence:'author',reviewer:'author',evidence:[{id:'html:p'},{id:'pdf:p'}]},{independence:'independent',reviewer:'independent',evidence:[{id:'html:p'},{id:'pdf:p'}]}]};assert.ok(q.validate(review,audit).some(e=>e.includes('independent')));review.qualityChecks.push(...quality('independent'));assert.deepEqual(q.validate(review,audit),[]);review.qualityChecks[0].status='not_applicable';assert.ok(q.validate(review,audit).length);
 console.log('PASS execution plan: fixed constraints, read-only resume, CAS/idempotency, evidence invalidation, stale delegation, dependency cycles, checkpoint relocation, locator-independent evidence, major-conclusion dual review');
 }finally{fs.rmSync(root,{recursive:true,force:true});}}
main().catch(e=>{console.error(e);process.exitCode=1;});
